blank_issues_enabled: false
contact_links:
  - name: 💎 Support AstralRinth Telegram
    about: Get support in our Telegram chat.
    url: https://xorison.dev/product/astralrinth/support
  - name: 🫶 Support Modrinth Portal
    about: Get support using through our support website.
    url: https://support.modrinth.com
